# Generated by Django 5.0.7 on 2025-02-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=45)),
                ("email", models.EmailField(max_length=45)),
                ("message", models.CharField(max_length=5000)),
            ],
            options={
                "db_table": "mensajes",
                "managed": True,
            },
        ),
    ]
