# Generated by Django 5.0.7 on 2025-02-15 18:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_rename_is_superadmin_account_is_superuser_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="membership_date",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
