# Generated by Django 5.0.7 on 2025-02-15 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Autor",
            fields=[
                ("id", models.AutoField(default=1, primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("slug", models.SlugField(default="default-slug", max_length=100)),
            ],
            options={
                "db_table": "autor",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Categoria",
            fields=[
                ("id", models.AutoField(default=1, primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("slug", models.SlugField(default="default-slug", max_length=100)),
            ],
            options={
                "db_table": "categoria",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Libro",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("titulo", models.CharField(max_length=100)),
                ("slug", models.SlugField(default="default-slug", max_length=100)),
                (
                    "slug_autor",
                    models.SlugField(default="defaul-slug-autor", max_length=100),
                ),
                (
                    "slug_categoria",
                    models.SlugField(default="defaul-slug-categoria", max_length=100),
                ),
                ("fecha", models.IntegerField(default=20240815)),
                ("valoracion", models.IntegerField(default=None)),
                (
                    "id_autor",
                    models.ForeignKey(
                        db_column="id_autor",
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="libros_por_autor",
                        to="resumenes.autor",
                    ),
                ),
                (
                    "id_categoria",
                    models.ForeignKey(
                        db_column="id_categoria",
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="libros_por_categoria",
                        to="resumenes.categoria",
                    ),
                ),
            ],
            options={
                "db_table": "libro",
                "managed": True,
            },
        ),
    ]
