# Generated by Django 5.0.7 on 2025-12-26 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
            ],
            options={
                'db_table': 'autor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
            ],
            options={
                'db_table': 'categoria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('fecha', models.DateField(default='2025-12-07')),
                ('link', models.URLField(blank=True)),
                ('num_valoraciones', models.IntegerField(default=0)),
                ('num_estrellas', models.IntegerField(default=0)),
                ('resumen', models.TextField(blank=True, null=True)),
                ('id_autor', models.ForeignKey(db_column='id_autor', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='libros_por_autor', to='resumenes.autor')),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='libros_por_categoria', to='resumenes.categoria')),
            ],
            options={
                'db_table': 'libro',
                'managed': True,
            },
        ),
    ]
