# Generated by Django 5.0.7 on 2025-12-27 22:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2025, 12, 27, 22, 33, 38, 677541, tzinfo=datetime.timezone.utc)),
        ),
    ]
