# Generated by Django 5.0.7 on 2025-03-14 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumenes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='slug_autor',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='slug_categoria',
        ),
    ]
