# Generated by Django 5.0.7 on 2026-04-09 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumenes', '0003_alter_libro_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2026, 4, 9, 20, 31, 32, 191264, tzinfo=datetime.timezone.utc)),
        ),
    ]
