# Generated by Django 5.0.7 on 2025-12-04 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumenes', '0003_libro_isbn_libro_link_alter_autor_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='valoracion',
        ),
        migrations.AddField(
            model_name='libro',
            name='num_estrellas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='libro',
            name='num_valoraciones',
            field=models.IntegerField(default=0),
        ),
    ]
