# Generated by Django 5.0.7 on 2026-09-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumenes', '0004_alter_libro_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='resumen',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='id_autor',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='id_categoria',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='link',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='slug',
        ),
        migrations.AddField(
            model_name='libro',
            name='autores',
            field=models.ManyToManyField(blank=True, related_name='libros', to='resumenes.autor'),
        ),
        migrations.AddField(
            model_name='libro',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='libros', to='resumenes.categoria'),
        ),
        migrations.AddField(
            model_name='libro',
            name='editorial',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='fecha_publicacion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='google_books_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='google_num_valoraciones',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='libro',
            name='google_valoracion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='idioma',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='isbn_10',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='isbn_13',
            field=models.CharField(blank=True, db_index=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='paginas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='portada',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='num_estrellas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='libro',
            name='num_valoraciones',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
