# Generated by Django 5.0.7 on 2025-12-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumenes', '0004_remove_libro_valoracion_libro_num_estrellas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='fecha',
            field=models.DateField(default='2025-12-07'),
        ),
    ]
