# Generated by Django 5.0.7 on 2026-09-07 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumenes', '0005_rename_resumen_libro_descripcion_remove_libro_fecha_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LibroUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_libro', to='resumenes.libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'libro_usuario',
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='librousuario',
            constraint=models.UniqueConstraint(fields=('usuario', 'libro'), name='unique_usuario_libro'),
        ),
    ]
