# Generated by Django 5.0.7 on 2025-12-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumenes', '0005_alter_libro_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='resumen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
